### ISSUE TITLE
ipad 12.9 first gen 14.7.1

### ISSUE THREAD

**Issue by jesussmile** [asdfugil/checkn1x_a9x_kerninfo_pongoOS#2]
I was on iPad 12.9 first gen wifi on 14.5.1 and the jailbreak worked flawlessly. I have tried numerous solutions but only your method worked. For some reason I am on 14.7.1, checkra1n is not supported. Is it still possible to jailbreak? I tried the odyssey option but nothing happens.

**Comment by asdfugil** [comment]
Odysseyra1n is fixed
