### ISSUE TITLE
release 14.5-a9x-2 issue installing Sileo

### ISSUE THREAD

**Issue by Nemura** [asdfugil/checkn1x_a9x_kerninfo_pongoOS#5]
On step 4 - installing Sileo, I get a dpkg error "org.coolstar.sileo_2.1-1_iphoneos-arm.deb is not a Debian format archive" after which it goes on to finish with "done bootsrapping your device" but didn't install Sileo.

I was able to work around this using this release to do the jailbreak with Checkra1n and afterwards switching to the latest (v2.14) raspberryenvoie/odysseyn1x to run odysseyra1n.

The might be a version mismatch of the script.

**Comment by asdfugil** [comment]
release soon
